# Numpy - Numeric Python

#### The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [ ]:
!pip install pandas

1D, 2D, 3D,....

In [2]:
l1=[1,2,3,4,5,6,7]  #1D array
n1=np.array(l1)
n1

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
n2 = np.array([[1,2,3,4,5,6,7], [4,2,3,1]])
n2

<ipython-input-3-8726eeed7b25>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  n2 = np.array([[1,2,3,4,5,6,7], [4,2,3,1]])


array([list([1, 2, 3, 4, 5, 6, 7]), list([4, 2, 3, 1])], dtype=object)

In [6]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
 dtype = float)

In [7]:
a

array([1, 2, 3])

In [8]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [16]:
#array of zeros
#np.zeros((no. of rows,no. of columns))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
#array of ones

np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
#array of evenly spaced values(stepwise)
#np.arange(start,end,difference)
np.arange(7,48,3)

array([ 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46])

In [23]:
#creates an array of evenly spaced values
#np.linspace(start,end,total no. of numbers required)
np.linspace(1,3.5,10)

array([1.        , 1.27777778, 1.55555556, 1.83333333, 2.11111111,
       2.38888889, 2.66666667, 2.94444444, 3.22222222, 3.5       ])

In [28]:
#creates a constant array
#np.full((no. of rows, no. of cols), the required number)
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [30]:
#creates a AXA identity matrix
#np.eye(x)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#creates an array of random numbers
np.random.random((3,2))

array([[0.20547885, 0.06931517],
       [0.36808898, 0.22375904],
       [0.19750842, 0.59823003]])

In [36]:
np.empty((2,3))

array([[0.20547885, 0.06931517, 0.36808898],
       [0.22375904, 0.19750842, 0.59823003]])

### Data types

np.int64                 Signed 64-bit integer types
np.float32               Standard double-precision floating point
np.complex               Complex numbers represented by 128 floats
np.bool                  Boolean type storing TRUE and FALSE values
np.object                Python object type
np.string_               Fixed-length string type
np.unicode_              Fixed-length unicode type

###  Inspecting array

a.shape                  Array dimensions
len(a)                   Length of array
b.ndim                   Number of array dimensions
e.size                   Number of array elements
b.dtype                  Data type of array elements
b.dtype.name             Name of data type
b.astype(int)            sConvert an array to a different type


In [38]:
##Asking for help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


### Arithmetic Operations

In [3]:
a = np.array((1,2,3,4))
b = np.array([(7,2,1,3),(3,1,2,4)])

In [8]:
a

array([1, 2, 3, 4])

In [9]:
b

array([[7, 2, 1, 3],
       [3, 1, 2, 4]])

In [4]:
c = a-b
c

array([[-6,  0,  2,  1],
       [-2,  1,  1,  0]])

In [5]:
c=a+b
c

array([[8, 4, 4, 7],
       [4, 3, 5, 8]])

In [6]:
c= a*b
c

array([[ 7,  4,  3, 12],
       [ 3,  2,  6, 16]])

In [7]:
c = a/b
c

array([[0.14285714, 1.        , 3.        , 1.33333333],
       [0.33333333, 2.        , 1.5       , 1.        ]])

In [48]:
c = b/a
a

array([1, 2, 3, 4])

In [50]:
c = b*a
c

array([[ 7,  4,  3, 12],
       [ 3,  2,  6, 16]])

In [51]:
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)

array([[0.14285714, 1.        , 3.        , 1.33333333],
       [0.33333333, 2.        , 1.5       , 1.        ]])

In [56]:
print('#Exponentiation')
print(np.exp(b))                  #Exponentiation
print('#Squareroot')
print(np.sqrt(b))                 #Square root
print('#Sines')
print(np.sin(a))                  #Print sines of an array
print('#Cosines')
print(np.cos(b))                  #Element-wise cosine
print('#Natural log')
print(np.log(a))                  #Element-wise natural logarithm
print('#Dot product')
print(b.dot(c))                   #Dot product

#Exponentiation
[[1096.63315843    7.3890561     2.71828183   20.08553692]
 [  20.08553692    2.71828183    7.3890561    54.59815003]]
#Squareroot
[[2.64575131 1.41421356 1.         1.73205081]
 [1.73205081 1.         1.41421356 2.        ]]
#Sines
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
#Cosines
[[ 0.75390225 -0.41614684  0.54030231 -0.9899925 ]
 [-0.9899925   0.54030231 -0.41614684 -0.65364362]]
#Natural log
[0.         0.69314718 1.09861229 1.38629436]
#Dot product


ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

### Comparison

In [58]:
a == b                 #Element-wise comparison
a < 2                  #Element-wise comparison
np.array_equal(a, b)   #Array-wise comparison

False

### Aggregate functions

In [65]:
a.sum()                #Array-wise sum
a.min()                #Array-wise minimum value
b.max(axis=0)          #Maximum value of an array row
b.cumsum(axis=1)       #Cumulative sum of the elements
a.mean()               #Mean
np.mean(a)
np.median(b)           #Median
np.corrcoef(b)         #Correlation coefficient
np.std(b)              #Standard deviation

1.8328597873268975

### Copying Arrays

In [66]:
h = a.view()          #Create a view of the array with the same data
np.copy(a)            #Create a copy of the array
h = a.copy()          #Create a deep copy of the array
h

array([1, 2, 3, 4])

### Sorting Arrays

In [67]:
a.sort()              #Sort an array
c.sort(axis=0)        #Sort the elements of an array's axis

### Array Manipulation

#Transposing Array
i = np.transpose(b)    
i.T 


#Changing Array Shape
b.ravel()                              Flatten the array
g.reshape(3,-2)                        Reshape, but don’t change data


#Adding/Removing Elements
h.resize((2,6))                        Return a new array with shape (2,6)
np.append(h,g)                         Append items to an array
np.insert(a, 1, 5)                     Insert items in an array
np.delete(a,[1])                       Delete items from an array


#Combining Arrays
np.concatenate((a,d),axis=0)           Concatenate arrays
np.vstack((a,b))                       Stack arrays vertically (row-wise)
np.r_[e,f]                             Stack arrays vertically (row-wise)
np.hstack((e,f))                       Stack arrays horizontally (column-wise)
np.column_stack((a,d))                 Create stacked column-wise arrays
np.c_[a,d]                             Create stacked column-wise arrays


#Splitting Arrays
np.hsplit(a,3)                         Split the array horizontally at the 3rd
np.vsplit(c,2)                         Split the array vertically at the 2nd index


### Slicing, Subsetting

#Subsetting
a[2]                         Select the element at the 2nd index 3
b[1,2]                       Select the element at row 1 column 2


#Slicing
a[0:2]                       Select items at index 0 and 1
b[0:2,1]                     Select items at rows 0 and 1 in column 1


b[:1]                        Select all items at row 0
c[1,...]                     Same as [1,:,:]
a[ : :-1]                    Reversed array a